// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaweOaJQZDjaXXYsL6lSF7g6-5DFGv9yQ',
    appId: '1:254860124463:web:6582d5b11d31738eccc1da',
    messagingSenderId: '254860124463',
    projectId: 'alarmle',
    authDomain: 'alarmle.firebaseapp.com',
    storageBucket: 'alarmle.firebasestorage.app',
    measurementId: 'G-45SV5LDT85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8KLqFUXzgJQqML9Vpc0URXMJUelg0ew',
    appId: '1:254860124463:android:0630651c0cd09f14ccc1da',
    messagingSenderId: '254860124463',
    projectId: 'alarmle',
    storageBucket: 'alarmle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63kWneWTf9HMmyfIDVMyhM-VYGsnOTKI',
    appId: '1:254860124463:ios:d4c34bb63ea6bac4ccc1da',
    messagingSenderId: '254860124463',
    projectId: 'alarmle',
    storageBucket: 'alarmle.firebasestorage.app',
    iosBundleId: 'com.CapyOtter.alarmle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA63kWneWTf9HMmyfIDVMyhM-VYGsnOTKI',
    appId: '1:254860124463:ios:d4c34bb63ea6bac4ccc1da',
    messagingSenderId: '254860124463',
    projectId: 'alarmle',
    storageBucket: 'alarmle.firebasestorage.app',
    iosBundleId: 'com.CapyOtter.alarmle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaweOaJQZDjaXXYsL6lSF7g6-5DFGv9yQ',
    appId: '1:254860124463:web:03f28e8fdce58950ccc1da',
    messagingSenderId: '254860124463',
    projectId: 'alarmle',
    authDomain: 'alarmle.firebaseapp.com',
    storageBucket: 'alarmle.firebasestorage.app',
    measurementId: 'G-8BQDE46HZY',
  );
}